//idea comes from: https://github.com/anson627/leetcode/blob/master/Permutations/src/Permutations.cpp
//All permutations can be generated by swapping
import java.util.*;

public class Permutations {
	public ArrayList<ArrayList<Integer>> permute(int[] num) {
		// Start typing your Java solution below
		// DO NOT write main() function
		ArrayList<ArrayList<Integer>> result = new ArrayList<ArrayList<Integer>>();
		permuteHelper(result, num, 0);
		return result;
	}

	public void permuteHelper(ArrayList<ArrayList<Integer>> result, int[] num,
			int i) {
		if (i < 0) {
			return;
		}
		if (i == num.length) {
			ArrayList<Integer> permutation = arrayToArrayList(num);
			result.add(permutation);
		} else {
			for (int j = i; j < num.length; j++) {// use swap to generate
													// permutations
				swap(num, i, j);
				permuteHelper(result, num, i + 1);
				swap(num, i, j);
			}

		}
		return;
	}

	public void swap(int[] num, int i, int j) {
		int temp = num[i];
		num[i] = num[j];
		num[j] = temp;
	}

	public ArrayList<Integer> arrayToArrayList(int[] num) {
		ArrayList<Integer> result = new ArrayList<Integer>();
		for (int i = 0; i < num.length; i++) {
			result.add(num[i]);
		}
		return result;
	}

}
